changelog:
  categories:
    - title: 🚀 Endringer
      labels:
        - "*"
      exclude:
        labels:
          - dependencies

    - title: 📦 Avhengigheter
      labels:
        - dependencies
