nodeLinker: node-modules

npmMinimalAgeGate: 2880

npmPreapprovedPackages:
  - '@navikt/*'
  - 'react@19.2.1'
  - 'react-dom@19.2.1'
  - 'next@16.0.7'
  - 'eslint-config-next@16.0.7'
  - '@next/eslint-plugin-next@16.0.7'
  - '@next/env@16.0.7'
  - '@next/swc-darwin-x64@16.0.7'
  - '@next/swc-darwin-arm64@16.0.7'
  - '@next/swc-darwin-x64@16.0.7'
  - '@next/swc-linux-arm64-gnu@16.0.7'
  - '@next/swc-linux-arm64-musl@16.0.7'
  - '@next/swc-linux-x64-gnu@16.0.7'
  - '@next/swc-linux-x64-musl@16.0.7'
  - '@next/swc-win32-arm64-msvc@16.0.7'
  - '@next/swc-win32-x64-msvc@16.0.7'

npmScopes:
  navikt:
    npmAlwaysAuth: true
    npmAuthToken: '${NODE_AUTH_TOKEN:-}'
    npmRegistryServer: 'https://npm.pkg.github.com'
