nodeLinker: node-modules

npmMinimalAgeGate: 2880

npmPreapprovedPackages:
  - '@navikt/*'

npmScopes:
  navikt:
    npmAlwaysAuth: true
    npmAuthToken: '${NODE_AUTH_TOKEN:-}'
    npmRegistryServer: 'https://npm.pkg.github.com'
