apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: oasis-idporten
  namespace: oasis-maintainers
  labels:
    team: oasis-maintainers
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: "/api/internal/isalive"
    initialDelay: 1
  readiness:
    path: "/api/internal/isready"
    initialDelay: 1
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 64Mi
  ingresses:
    - https://oasis-idporten.intern.dev.nav.no
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: oasis-idporten
