name: Release 4.0.0 beta

on:
  push:
    branches:
      - feat/texas

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      packages: "write"
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com
          cache: npm

      - run: npm ci
      - run: npm test
      - run: npm run lint
      - run: npm run build-lib

      - run: |
          TEMP_VERSION=$(date +'%Y%m%d%H%M%S')
          jq --arg v "4.0.0-$TEMP_VERSION" '.version = $v' package.json > package.tmp.json && mv package.tmp.json package.json

          npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: oasis
